// Recipe API

GET localhost:7070/api/v1/recipes
Authorization: Bearer {{token}}

###

GET http://localhost:7070/api/v1/recipes/10
Authorization: Bearer {{token}}

###

POST localhost:7070/api/v1/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "recipeName": "Example Veggie Dish",
  "recipeImg": "https://i.imgur.com/vwx234.jpg",
  "recipeDescription": "A quick and nutritious example option",
  "recipeType": "LUNCH",
  "recipePreptime": 15,
  "recipeIngredients": "4 slices turkey, 1 whole grain wrap, lettuce, tomato, cucumber, hummus",
  "recipeDirections": "1. Spread hummus on wrap\n2. Layer turkey slices and veggies\n3. Roll up the wrap"
}

###

PUT localhost:7070/api/v1/recipes/37
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "recipeName": "Example Veggie Dish Updated",
  "recipeImg": "https://i.imgur.com/vwx234.jpg",
  "recipeDescription": "A quick and nutritious example option",
  "recipeType": "LUNCH",
  "recipePreptime": 15,
  "recipeIngredients": "4 slices turkey, 1 whole grain wrap, lettuce, tomato, cucumber, hummus",
  "recipeDirections": "1. Spread hummus on wrap\n2. Layer turkey slices and veggies\n3. Roll up the wrap"
}

###

DELETE localhost:7070/api/v1/recipes/37
Authorization: Bearer {{token}}